AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Just Another Serverless Rest API

Globals:
  Function:
    Runtime: nodejs8.10

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  GetBasePathFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Timeout: 3
      Handler: index.handleGetBasePath
      Events:
        GetBasePath:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: GET
            Auth:
              Authorizer: NONE

  BulkWriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1024
      Timeout: 120
      Handler: index.handleBulkWrite
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Store
      Environment:
        Variables:
          TABLE_NAME: !Ref Store
      Events:
        BulkWriteOperation:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /import/{className}
            Method: POST

  QueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Timeout: 3
      Handler: index.handleQuery
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Store
      Environment:
        Variables:
          TABLE_NAME: !Ref Store
      Events:
        FindObjects:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /classes/{className}
            Method: GET
        ReadObject:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /classes/{className}/{objectId}
            Method: GET

  WriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Timeout: 3
      Handler: index.handleWrite
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Store
      Environment:
        Variables:
          TABLE_NAME: !Ref Store
      Events:
        CreateObject:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /classes/{className}
            Method: POST
        UpdateObject:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /classes/{className}/{objectId}
            Method: PUT
        DeleteObject:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /classes/{className}/{objectId}
            Method: DELETE

  Store:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: 'objectId'
          KeyType: 'HASH'
      AttributeDefinitions:
        - AttributeName: 'objectId'
          AttributeType: 'S'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  ApiId:
    Description: 'API Gateway Id'
    Value: !Ref ApiGateway

  ApiUrl:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    
